### ISSUE TITLE
[Dashboard] wallets of unsupported network cause an error

### ISSUE THREAD

**Issue by dated** [PayvoHQ/wallet#793]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'network')
    at e3.value (wallet.ts:108:15)
    at use-wallet-config.ts:22:29
    at Array.map (<anonymous>)
    at useWalletConfig (use-wallet-config.ts:22:6)
    at useWalletFilters (hooks.ts:10:95)
    at Dashboard (Dashboard.tsx:26:33)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
```

**Comment by alesmit** [comment]
@dated I played around with enabling/disabling networks but wasn't able to make this error show. Which steps do you make that lead up to this error?

**Comment by alesmit** [comment]
Discussion in Slack https://cryptoarkproject.slack.com/archives/CJFKZSV61/p1642490980070200
